### ISSUE TITLE
Typo in repo description

### ISSUE THREAD

**Issue by Rikk** [piroor/makexpi#3]
Where it reads
>Build scripts for XPI: creating, publishing and **prividing** auto-update.

should read
>Build scripts for XPI: creating, publishing and **providing** auto-update.

# @piroor Why you abandoned [Multiple Tab Handler](https://github.com/piroor/multipletab)?

**Comment by Rikk** [comment]
Thanks!

**Comment by piroor** [comment]
Oops, thanks! MTH is still active and recently released at 2015-11-30.

**Comment by Rikk** [comment]
Yea, I know --glad to see you working on it again--, anyway this is old post from July just for bringing attention to MTH... I think I should have deleted it long ago, but completely forgot.
