### ISSUE TITLE
gcp check in makexpi.sh is not reliable

### ISSUE THREAD

**Issue by HakanSiktas** [piroor/makexpi#4]
On all my systems gcp is an alias for git cherry-pick and this line
https://github.com/piroor/makexpi/blob/master/makexpi.sh#L65

is not sufficient to check if gcp is available.
As a workaround I just entered my absolute path to cp or GNU cp two lines below that check.

This could be an issue for a lot users as these aliases are part of the default setup of oh-my-zsh: https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh#L82

**Comment by piroor** [comment]
Thanks. I've added a code to ignore gcp if it is not the GNU coreutils's cp, at 236251ec94b2604165a33de560c67e5509c8d785. Does it work for you?

**Comment by HakanSiktas** [comment]
Yes, with that commit I have no problems with building TST on both Cygwin and OS X. Thank you for the quick response. :+1:
